#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Write a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

best_school="Best School"
bad_luck="bad luck"
good_luck="good luck"
i="0"

while [ $i -lt 10 ]; do
  if [ $i -eq 3 ]; then
   	echo "$bad_luck"
  elif [ $i -eq 7 ]; then
        echo "$good_luck"
  else
        echo "$best_school"
  fi
  ((i++))
done
